### ISSUE TITLE
TypeError: result.concat is not a function

### ISSUE THREAD

**Issue by fannarsh** [tagplay/slack-client#1]
```
[2019-09-10T01:45:22.221Z]  WARN: slack-connections/885543 on 75fae492e1af: Error fetching channels for connection (version=1.2.0, worker=64)
    TypeError: result.concat is not a function
        at SlackAPI.getPaginated (/app/node_modules/@tagplay/slack-client/index.js:71:26)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    --
```

**Comment by fannarsh** [comment]
An internal fix in the service this is used has been added in https://github.com/tagplay/slack-connections/commit/5bf9716bd7ec5e4398908f952dd95ef0b46312e9
